project: #项目信息
 name: xiu-xing-server


spring: #应用配置
  application:
    name: ${project.name}
  jackson:
    default-property-inclusion: non_null
server: #系统配置
  port: 8888
  servlet:
    context-path: /xiuXing

master: #主数据库配置
 db:
  type: mysql
  url: jdbc:mysql://localhost:3306/xiu_xing?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  username: root
  password: fyjjhy123!@#

cache: #缓存配置
  model: REDIS
  redis:
   address: 127.0.0.1:6379

extend:
  errorMessage:
    files:
      errorMessage_xiu_xing.properties